font_family FiraCode Nerd Font
bold_font auto
italic_font auto
bold_italic_font auto

font_size 12

disasble_ligatures never

open_url_with firefox

copy_on_select yes

background_opacity .85
confirm_os_window_close 0
